name: shoppingapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+61


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  intl: ^0.19.0
  get_it: ^7.6.7
  location: ^5.0.3
  geocoding: ^2.1.1
  auto_route: ^7.8.4
  google_place: ^0.4.7
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  cloud_firestore: ^4.15.4
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_login_facebook: ^1.9.0
  geolocator: ^10.1.0
  flutter_vibrate: ^1.3.0
  
  #ui
  image: ^4.1.6
  lottie: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  sms_autofill: ^2.2.0
  google_fonts: ^4.0.4
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.9
  flutter_remix: ^0.0.3
  connectivity_plus: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.3.10
  flutter_advanced_switch: ^3.0.1
  flutter_share: ^2.0.0
  pull_to_refresh: ^2.0.0
  flutter_masked_text2: ^0.9.1
  image_cropper: ^4.0.1
  floating_draggable_widget: ^2.1.5
  google_maps_flutter: ^2.5.3
  flutter_html: ^3.0.0-beta.2
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  proste_indexed_stack: ^0.2.4
  osm_nominatim: ^2.0.1
  flutter_carousel_slider: ^1.1.0
  jiffy: ^6.2.2
  flutter_staggered_animations: ^1.1.1
  upgrader: ^9.0.0
  like_button: ^2.0.5
  carousel_slider: ^4.2.1
  map_launcher: ^3.1.0
  rating_summary: ^1.0.2+1
  readmore: ^2.2.0

#firebase
  firebase_dynamic_links: ^5.4.13
  firebase_messaging: ^14.7.15
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/customer.png'
